id: I4184DBDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:00:30+00:00'
last_modified: '2022-06-07T16:13:45.417129+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ58512
  title: རྐ་སར་འདུས་བཟང་ཆོས་གླིང་དུ་བཞུགས་པའི་དཔེ་རྙིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6A36:
      image_group_id: I4CZ74163
      title: ''
      total_pages: 278
      order: 1
      base_file: 6A36.txt
    E366:
      image_group_id: I4CZ74164
      title: ''
      total_pages: 568
      order: 2
      base_file: E366.txt
    B041:
      image_group_id: I4CZ74165
      title: ''
      total_pages: 560
      order: 3
      base_file: B041.txt
    688F:
      image_group_id: I4CZ74166
      title: ''
      total_pages: 542
      order: 4
      base_file: 688F.txt
    '4561':
      image_group_id: I4CZ74167
      title: ''
      total_pages: 320
      order: 5
      base_file: 4561.txt
    AE8E:
      image_group_id: I4CZ74168
      title: ''
      total_pages: 1488
      order: 6
      base_file: AE8E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
