id: I4184DBDB
legacy_id: P002923
ocr_import_info:
  bdrc_scan_id: W4CZ58512
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T22:51:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:38:28.828716+00:00'
last_modified: 2022-09-04 04:40:18.031186
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ58512
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ58512
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྐ་སར་འདུས་བཟང་ཆོས་གླིང་དུ་བཞུགས་པའི་དཔེ་རྙིང་།
statistics:
  ocr_word_mean_confidence_index: 0.7208752769175187
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I4CZ74163:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74163
      total_pages: 278
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74163.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7386835018455428
    legacy_id: v001
  I4CZ74164:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74164
      total_pages: 568
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CZ74164.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7596395625607938
    legacy_id: v002
  I4CZ74167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74167
      total_pages: 320
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4CZ74167.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7602033460232674
    legacy_id: v005
  I4CZ74166:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74166
      total_pages: 542
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4CZ74166.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6428932031150055
    legacy_id: v004
  I4CZ74165:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74165
      total_pages: 560
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4CZ74165.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.753821812658524
    legacy_id: v003
  I4CZ74168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74168
      total_pages: 1488
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4CZ74168.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.725328272688557
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
